In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\house_prices_by_town_v2.csv")
df

,Property ID,Town,Property Type,Bedrooms,Bathrooms,Square Feet,Price ($)
0,PROP-1001,Austin,Single Family,1,3.5,1926,485352
1,PROP-1002,Austin,Townhouse,2,3.5,1219,401051
2,PROP-1003,Austin,Single Family,5,2.5,930,183210
3,PROP-1004,Austin,Single Family,2,1.5,2869,562324
4,PROP-1005,Austin,Townhouse,5,2.5,1702,517408
...,...,...,...,...,...,...,...
95,PROP-1096,San Marcos,Single Family,4,3.0,1578,402390
96,PROP-1097,San Marcos,Single Family,4,1.0,2929,957783
97,PROP-1098,San Marcos,Townhouse,3,2.5,1086,297564
98,PROP-1099,San Marcos,Condo,1,3.5,2030,647570
99,PROP-1100,San Marcos,Condo,4,2.0,2448,648720

In [3]:
dummies = pd.get_dummies(df[['Town', 'Property Type']]).astype(int)
dummies

,Town_Austin,Town_Buda,Town_Cedar Park,Town_Georgetown,Town_Kyle,Town_Lakeway,Town_Leander,Town_Pflugerville,Town_Round Rock,Town_San Marcos,Property Type_Condo,Property Type_Multi-Family,Property Type_Single Family,Property Type_Townhouse
0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1,0,0,0,0,0,0,0,0,0,0,0,1,0
3,1,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,1,0,0,1,0
96,0,0,0,0,0,0,0,0,0,1,0,0,1,0
97,0,0,0,0,0,0,0,0,0,1,0,0,0,1
98,0,0,0,0,0,0,0,0,0,1,1,0,0,0
99,0,0,0,0,0,0,0,0,0,1,1,0,0,0

In [4]:
merged = pd.concat([df, dummies], axis='columns')
merged

,Property ID,Town,Property Type,Bedrooms,Bathrooms,Square Feet,Price ($),Town_Austin,Town_Buda,Town_Cedar Park,...,Town_Kyle,Town_Lakeway,Town_Leander,Town_Pflugerville,Town_Round Rock,Town_San Marcos,Property Type_Condo,Property Type_Multi-Family,Property Type_Single Family,Property Type_Townhouse
0,PROP-1001,Austin,Single Family,1,3.5,1926,485352,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,PROP-1002,Austin,Townhouse,2,3.5,1219,401051,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,PROP-1003,Austin,Single Family,5,2.5,930,183210,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,PROP-1004,Austin,Single Family,2,1.5,2869,562324,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,PROP-1005,Austin,Townhouse,5,2.5,1702,517408,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PROP-1096,San Marcos,Single Family,4,3.0,1578,402390,0,0,0,...,0,0,0,0,0,1,0,0,1,0
96,PROP-1097,San Marcos,Single Family,4,1.0,2929,957783,0,0,0,...,0,0,0,0,0,1,0,0,1,0
97,PROP-1098,San Marcos,Townhouse,3,2.5,1086,297564,0,0,0,...,0,0,0,0,0,1,0,0,0,1
98,PROP-1099,San Marcos,Condo,1,3.5,2030,647570,0,0,0,...,0,0,0,0,0,1,1,0,0,0
99,PROP-1100,San Marcos,Condo,4,2.0,2448,648720,0,0,0,...,0,0,0,0,0,1,1,0,0,0

In [5]:
final = merged.drop(columns=['Town', 'Round Rock', 'Property Type', 'Property ID'], errors='ignore')
final

,Bedrooms,Bathrooms,Square Feet,Price ($),Town_Austin,Town_Buda,Town_Cedar Park,Town_Georgetown,Town_Kyle,Town_Lakeway,Town_Leander,Town_Pflugerville,Town_Round Rock,Town_San Marcos,Property Type_Condo,Property Type_Multi-Family,Property Type_Single Family,Property Type_Townhouse
0,1,3.5,1926,485352,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,2,3.5,1219,401051,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,5,2.5,930,183210,1,0,0,0,0,0,0,0,0,0,0,0,1,0
3,2,1.5,2869,562324,1,0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,2.5,1702,517408,1,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,3.0,1578,402390,0,0,0,0,0,0,0,0,0,1,0,0,1,0
96,4,1.0,2929,957783,0,0,0,0,0,0,0,0,0,1,0,0,1,0
97,3,2.5,1086,297564,0,0,0,0,0,0,0,0,0,1,0,0,0,1
98,1,3.5,2030,647570,0,0,0,0,0,0,0,0,0,1,1,0,0,0
99,4,2.0,2448,648720,0,0,0,0,0,0,0,0,0,1,1,0,0,0

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [7]:
X = final.drop(columns=['Price ($)'], errors='ignore')
X

,Bedrooms,Bathrooms,Square Feet,Town_Austin,Town_Buda,Town_Cedar Park,Town_Georgetown,Town_Kyle,Town_Lakeway,Town_Leander,Town_Pflugerville,Town_Round Rock,Town_San Marcos,Property Type_Condo,Property Type_Multi-Family,Property Type_Single Family,Property Type_Townhouse
0,1,3.5,1926,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,2,3.5,1219,1,0,0,0,0,0,0,0,0,0,0,0,0,1
2,5,2.5,930,1,0,0,0,0,0,0,0,0,0,0,0,1,0
3,2,1.5,2869,1,0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,2.5,1702,1,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,3.0,1578,0,0,0,0,0,0,0,0,0,1,0,0,1,0
96,4,1.0,2929,0,0,0,0,0,0,0,0,0,1,0,0,1,0
97,3,2.5,1086,0,0,0,0,0,0,0,0,0,1,0,0,0,1
98,1,3.5,2030,0,0,0,0,0,0,0,0,0,1,1,0,0,0
99,4,2.0,2448,0,0,0,0,0,0,0,0,0,1,1,0,0,0

In [8]:
X = X.drop(columns=['Town_Austin', 'Property Type_Condo'])

In [9]:
y = final['Price ($)']
y

0     485352
1     401051
2     183210
3     562324
4     517408
       ...
95    402390
96    957783
97    297564
98    647570
99    648720
Name: Price ($), Length: 100, dtype: int64

In [10]:
model.fit(X, y)

LinearRegression()

In [11]:
print(model.n_features_in_)
print(list(X.columns))

15
['Bedrooms', 'Bathrooms', 'Square Feet', 'Town_Buda', 'Town_Cedar Park', 'Town_Georgetown', 'Town_Kyle', 'Town_Lakeway', 'Town_Leander', 'Town_Pflugerville', 'Town_Round Rock', 'Town_San Marcos', 'Property Type_Multi-Family', 'Property Type_Single Family', 'Property Type_Townhouse']

In [12]:
sample_house = pd.DataFrame([{
    'Bedrooms': 3,
    'Bathrooms': 2,
    'Square Feet': 2000,
    'Town_Buda': 1,        
    'Town_Cedar Park': 0,
    'Town_Georgetown': 0,
    'Town_Kyle': 0,
    'Town_Lakeway': 0,
    'Town_Leander': 0,
    'Town_Pflugerville': 0,
    'Town_Round Rock': 0,
    'Town_San Marcos': 0,
    'Property Type_Multi-Family': 0,
    'Property Type_Single Family': 1,
    'Property Type_Townhouse': 0
}])

sample_house = sample_house.reindex(columns=X.columns, fill_value=0)

predicted_price = model.predict(sample_house)
print("Predicted House Price:", predicted_price)

Predicted House Price: [497578.01225371]

In [13]:
model.score(X, y)

0.8776968862706578

In [14]:
df

,Property ID,Town,Property Type,Bedrooms,Bathrooms,Square Feet,Price ($)
0,PROP-1001,Austin,Single Family,1,3.5,1926,485352
1,PROP-1002,Austin,Townhouse,2,3.5,1219,401051
2,PROP-1003,Austin,Single Family,5,2.5,930,183210
3,PROP-1004,Austin,Single Family,2,1.5,2869,562324
4,PROP-1005,Austin,Townhouse,5,2.5,1702,517408
...,...,...,...,...,...,...,...
95,PROP-1096,San Marcos,Single Family,4,3.0,1578,402390
96,PROP-1097,San Marcos,Single Family,4,1.0,2929,957783
97,PROP-1098,San Marcos,Townhouse,3,2.5,1086,297564
98,PROP-1099,San Marcos,Condo,1,3.5,2030,647570
99,PROP-1100,San Marcos,Condo,4,2.0,2448,648720

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
dfle = df
dfle = dfle.drop(columns=['Property ID'], errors='ignore')
dfle["Town"] = le.fit_transform(dfle["Town"])
dfle["Property Type"] = le.fit_transform(dfle["Property Type"])
dfle

    Town  Property Type  Bedrooms  Bathrooms  Square Feet  Price ($)
0      0              2         1        3.5         1926     485352
1      0              3         2        3.5         1219     401051
2      0              2         5        2.5          930     183210
3      0              2         2        1.5         2869     562324
4      0              3         5        2.5         1702     517408
..   ...            ...       ...        ...          ...        ...
95     9              2         4        3.0         1578     402390
96     9              2         4        1.0         2929     957783
97     9              3         3        2.5         1086     297564
98     9              0         1        3.5         2030     647570
99     9              0         4        2.0         2448     648720

[100 rows x 6 columns]

In [17]:
X = dfle[['Square Feet', 'Bedrooms', 'Bathrooms', 'Town', 'Property Type']]
X

    Square Feet  Bedrooms  Bathrooms  Town  Property Type
0          1926         1        3.5     0              2
1          1219         2        3.5     0              3
2           930         5        2.5     0              2
3          2869         2        1.5     0              2
4          1702         5        2.5     0              3
..          ...       ...        ...   ...            ...
95         1578         4        3.0     9              2
96         2929         4        1.0     9              2
97         1086         3        2.5     9              3
98         2030         1        3.5     9              0
99         2448         4        2.0     9              0

[100 rows x 5 columns]

In [18]:
y = dfle['Price ($)']
y

0     485352
1     401051
2     183210
3     562324
4     517408
       ...
95    402390
96    957783
97    297564
98    647570
99    648720
Name: Price ($), Length: 100, dtype: int64

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
import pandas as pd

X = dfle[['Square Feet', 'Bedrooms', 'Bathrooms', 'Town', 'Property Type']]
y = dfle['Price ($)']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), [3, 4])
    ],
    remainder='passthrough'
)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [24]:
model.fit(X, y)

# 5. Make a prediction (passing a DataFrame with the same original column names)
sample_house = pd.DataFrame([[2400, 3, 2, 0, 1]], 
                            columns=['Square Feet', 'Bedrooms', 'Bathrooms', 'Town', 'Property Type'])

predicted_price = model.predict(sample_house)
print("Predicted House Price:", predicted_price)

Predicted House Price: [573487.54657816]